#!/usr/bin/env bash

langs=("perl")

localtime=$(date '+%Y%m%d%H%M%S')

for lang in "${langs[@]}"; do
	mkdir -p "./target/$lang" && touch "./target/$lang/$lang-hook$localtime.log"
done

### analyce all commited files
for file in $(git diff --cached --name-only --diff-filter=d); do
	case $(file -bi $file)$file in
		*"perl"*|*.pl|*.pm)
			
			### format and analyce files
			perltidy --pro=./hook-config/perl/.perltidyrc "$file" >> "./target/perl/perl-hook$localtime.log"
			if [ $? != 0 ]; then
				echo "################################################################################"
				echo "$file file was not formatted correctly or had errors. Check log file"
				echo "################################################################################"
				exit 1 
			fi

			mv "$file.tdy" "$file"
			perlcritic --profile ./hook-config/perl/.perlcriticrc "$file" >> ./target/perl/perl-hook$localtime.log
			if [ $? != 0 ]; then
				echo "################################################################################"
				echo "$file did not pass PERLCRITIC configuration. Check log file"
				echo "################################################################################"
				exit 1 
			fi

			echo "##################################"
			echo "###$file had no errors"
			echo "##################################"
			;;

		*)
			echo ">>>> Skip file $file"
			;;
	esac
	git add "$file"
done

exit 0
