#!/usr/bin/env bash

commit_msg_file=$(git rev-parse --git-dir)/COMMIT_EDITMSG
commit_msg=$(cat "$commit_msg_file")
tmp="/tmp/commit_temp_message"

echo "$commit_msg" >> "$tmp"
echo "" >>   "$tmp"

git diff --name-status HEAD~1 | while read -r file ; do
	type=$(echo "$file" | cut -f1 -d' ' )
	name=$( echo "$file" | cut -f2 -d' ' )
	case "$type" in
		"M") translated_status="modified";;
		"A") translated_status="added";;
		"D") translated_status="deleted";;
		"R") translated_status="renamed";;
		"C") translated_status="copied";;
		"U") translated_status="updated but unmerged";;
		*) translated_status="unknown";;
	esac
	echo "$translated_status: $name" >> "$tmp"
done

mv "$tmp" "$commit_msg_file"

exit 0
