#!/usr/bin/env bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

tmp="/tmp/commit_temp_message"
cat "$COMMIT_MSG_FILE" >> "$tmp"

## Remove unnecesarry content
sed -i '/^# Please enter the commit message for your changes\|^# with \|^$/d' "$tmp"
sed -i '/^# Changes to be committed:/d' "$tmp"
sed -i '/On branch/d; n; /Changes not staged for commit:/q' "$tmp"
sed -i '/Changes not staged for commit:/,$d' "$tmp"
sed -i '1s/$/\n/' "$tmp"

for file in "$(git diff --name-status HEAD~1)"; do
	translated_status=$(echo "$file" | cut -f1 -d' ' )
	name=$( echo "$file" | cut -f2 -d' ' )
	case "$type" in
		*"M"*) translated_status="modified";;
		*"A"*) translated_status="added";;
		*"D"*) translated_status="deleted";;
		*"R"*) translated_status="renamed";;
		*"C"*) translated_status="copied";;
		*"U*") translated_status="updated but unmerged";;
		*) translated_status="unknown";;
	esac
	echo "$translated_states: $name" >> "$tmp"
done
mv "$tmp" "$COMMIT_MSG_FILE"

exit 0
